apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledgerly.name" . }}-secrets
  labels:
    {{- include "ledgerly.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "postgres://{{ .Values.database.username }}:SUPER_SECRET_PASSWORD@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}?sslmode={{ .Values.database.sslmode }}"
  WEBHOOK_SECRET: "ledgerly_whsec_production_hmac_secret"
