package postgres_test

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gitlab.com/steph-ano/ledgerly/services/ledger/internal/domain"
	"gitlab.com/steph-ano/ledgerly/services/ledger/internal/storage/postgres"
)

func sha256Hex(s string) string {
	h := sha256.Sum256([]byte(s))
	return hex.EncodeToString(h[:])
}

func TestIntegration_AccountCreationAndBalance(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	ctx := context.Background()

	accID := uuid.New()
	acc, err := domain.NewAccount(accID, "client_test", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	require.NoError(t, err)

	err = accountRepo.Create(ctx, acc)
	require.NoError(t, err)

	retrieved, err := accountRepo.GetByID(ctx, accID)
	require.NoError(t, err)
	assert.Equal(t, accID, retrieved.ID)
	assert.Equal(t, domain.AccountTypeCustomer, retrieved.Type)
	assert.Equal(t, "USD", retrieved.Currency)

	bal, err := accountRepo.GetBalance(ctx, accID)
	require.NoError(t, err)
	assert.Equal(t, int64(0), bal.Debits)
	assert.Equal(t, int64(0), bal.Credits)
	assert.Equal(t, "USD", bal.Currency)
}

func TestIntegration_DoubleEntryTransaction(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	// Create customer and merchant accounts
	custAccID := uuid.New()
	merchAccID := uuid.New()

	custAcc, _ := domain.NewAccount(custAccID, "client_1", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	merchAcc, _ := domain.NewAccount(merchAccID, "client_1", domain.AccountTypeMerchant, "USD", time.Now().UTC())

	require.NoError(t, accountRepo.Create(ctx, custAcc))
	require.NoError(t, accountRepo.Create(ctx, merchAcc))

	// $100.00 (10000 cents): Customer Debit, Merchant Credit
	entries := []domain.Entry{
		{AccountID: custAccID, Amount: 10000, Direction: domain.DirectionDebit, Currency: "USD"},
		{AccountID: merchAccID, Amount: 10000, Direction: domain.DirectionCredit, Currency: "USD"},
	}

	txID := uuid.New()
	txEntity, err := domain.NewTransaction(
		txID,
		"client_1",
		"idem_key_1",
		sha256Hex("payload_1"),
		"Purchase Order 1001",
		entries,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	recordedTx, isNew, err := txRepo.RecordTransaction(ctx, txEntity, 0)
	require.NoError(t, err)
	assert.True(t, isNew)
	assert.Equal(t, txID, recordedTx.ID)

	// Verify balances:
	// Customer (Asset): 10000 debits, 0 credits
	custBal, err := accountRepo.GetBalance(ctx, custAccID)
	require.NoError(t, err)
	assert.Equal(t, int64(10000), custBal.Debits)
	assert.Equal(t, int64(0), custBal.Credits)

	// Merchant (Liability): 0 debits, 10000 credits
	merchBal, err := accountRepo.GetBalance(ctx, merchAccID)
	require.NoError(t, err)
	assert.Equal(t, int64(0), merchBal.Debits)
	assert.Equal(t, int64(10000), merchBal.Credits)
}

func TestIntegration_IdempotencySamePayload(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	accA := uuid.New()
	accB := uuid.New()
	accAObj, _ := domain.NewAccount(accA, "client_idem", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	accBObj, _ := domain.NewAccount(accB, "client_idem", domain.AccountTypeMerchant, "USD", time.Now().UTC())
	require.NoError(t, accountRepo.Create(ctx, accAObj))
	require.NoError(t, accountRepo.Create(ctx, accBObj))

	entries := []domain.Entry{
		{AccountID: accA, Amount: 5000, Direction: domain.DirectionDebit, Currency: "USD"},
		{AccountID: accB, Amount: 5000, Direction: domain.DirectionCredit, Currency: "USD"},
	}

	hash := sha256Hex("order_payload")
	txEntity, err := domain.NewTransaction(
		uuid.New(),
		"client_idem",
		"key_idempotent_test",
		hash,
		"Payment for Order 55",
		entries,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	// 1st request: new transaction
	tx1, isNew1, err := txRepo.RecordTransaction(ctx, txEntity, 0)
	require.NoError(t, err)
	assert.True(t, isNew1)

	// 2nd request: retry with identical payload and key
	txRetry, err := domain.NewTransaction(
		uuid.New(), // different random ID generated by client on retry, but same idempotency key and hash
		"client_idem",
		"key_idempotent_test",
		hash,
		"Payment for Order 55",
		entries,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	tx2, isNew2, err := txRepo.RecordTransaction(ctx, txRetry, 0)
	require.NoError(t, err)
	assert.False(t, isNew2, "retry must not be marked as new record")
	assert.Equal(t, tx1.ID, tx2.ID, "must return original transaction ID")
	assert.Equal(t, tx1.IdempotencyKey, tx2.IdempotencyKey)
	assert.Len(t, tx2.Entries, 2)

	// Verify balance was NOT double counted (should be exactly 5000)
	balA, err := accountRepo.GetBalance(ctx, accA)
	require.NoError(t, err)
	assert.Equal(t, int64(5000), balA.Debits)
}

func TestIntegration_IdempotencyPayloadMismatch(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	accA := uuid.New()
	accB := uuid.New()
	accAObj, _ := domain.NewAccount(accA, "client_mismatch", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	accBObj, _ := domain.NewAccount(accB, "client_mismatch", domain.AccountTypeMerchant, "USD", time.Now().UTC())
	require.NoError(t, accountRepo.Create(ctx, accAObj))
	require.NoError(t, accountRepo.Create(ctx, accBObj))

	entries := []domain.Entry{
		{AccountID: accA, Amount: 3000, Direction: domain.DirectionDebit, Currency: "USD"},
		{AccountID: accB, Amount: 3000, Direction: domain.DirectionCredit, Currency: "USD"},
	}

	tx1, err := domain.NewTransaction(
		uuid.New(),
		"client_mismatch",
		"reused_key",
		sha256Hex("payload_A"),
		"Original Transaction",
		entries,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	_, isNew, err := txRepo.RecordTransaction(ctx, tx1, 0)
	require.NoError(t, err)
	assert.True(t, isNew)

	// Second request with SAME key but DIFFERENT payload hash
	tx2, err := domain.NewTransaction(
		uuid.New(),
		"client_mismatch",
		"reused_key",
		sha256Hex("different_payload_B"),
		"Different Transaction",
		entries,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	_, _, err = txRepo.RecordTransaction(ctx, tx2, 0)
	assert.ErrorIs(t, err, domain.ErrIdempotencyKeyPayloadMismatch)
}

func TestIntegration_ConcurrentIdempotentRequests(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	accA := uuid.New()
	accB := uuid.New()
	accAObj, _ := domain.NewAccount(accA, "client_conc_idem", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	accBObj, _ := domain.NewAccount(accB, "client_conc_idem", domain.AccountTypeMerchant, "USD", time.Now().UTC())
	require.NoError(t, accountRepo.Create(ctx, accAObj))
	require.NoError(t, accountRepo.Create(ctx, accBObj))

	hash := sha256Hex("concurrent_idempotency_payload")
	idemKey := "key_concurrent_test"

	concurrency := 10
	var wg sync.WaitGroup
	results := make([]struct {
		tx    *domain.Transaction
		isNew bool
		err   error
	}, concurrency)

	for i := 0; i < concurrency; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			entries := []domain.Entry{
				{AccountID: accA, Amount: 1000, Direction: domain.DirectionDebit, Currency: "USD"},
				{AccountID: accB, Amount: 1000, Direction: domain.DirectionCredit, Currency: "USD"},
			}
			txEntity, err := domain.NewTransaction(
				uuid.New(),
				"client_conc_idem",
				idemKey,
				hash,
				"Concurrent Idempotent Request",
				entries,
				time.Now().UTC(),
			)
			if err != nil {
				results[idx].err = err
				return
			}

			recTx, isNew, err := txRepo.RecordTransaction(ctx, txEntity, 0)
			results[idx].tx = recTx
			results[idx].isNew = isNew
			results[idx].err = err
		}(i)
	}

	wg.Wait()

	newCount := 0
	existingCount := 0
	var expectedID uuid.UUID

	for _, res := range results {
		require.NoError(t, res.err)
		require.NotNil(t, res.tx)
		if expectedID == uuid.Nil {
			expectedID = res.tx.ID
		} else {
			assert.Equal(t, expectedID, res.tx.ID, "all concurrent requests must converge on same transaction ID")
		}

		if res.isNew {
			newCount++
		} else {
			existingCount++
		}
	}

	assert.Equal(t, 1, newCount, "exactly 1 request must be marked as new")
	assert.Equal(t, concurrency-1, existingCount, "remaining requests must be recognized as existing")

	// Verify balance was only credited once
	balA, err := accountRepo.GetBalance(ctx, accA)
	require.NoError(t, err)
	assert.Equal(t, int64(1000), balA.Debits)
}

func TestIntegration_NegativeBalancePolicyEnforcement(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	custAccID := uuid.New()
	merchAccID := uuid.New()
	platAccID := uuid.New()

	custAcc, _ := domain.NewAccount(custAccID, "client_policy", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	merchAcc, _ := domain.NewAccount(merchAccID, "client_policy", domain.AccountTypeMerchant, "USD", time.Now().UTC())
	platAcc, _ := domain.NewAccount(platAccID, "client_policy", domain.AccountTypePlatform, "USD", time.Now().UTC())

	require.NoError(t, accountRepo.Create(ctx, custAcc))
	require.NoError(t, accountRepo.Create(ctx, merchAcc))
	require.NoError(t, accountRepo.Create(ctx, platAcc))

	// 1. Attempting payout from merchant with 0 balance (merch debit > credit)
	// Merchant normal balance is CREDIT. Debit without prior credit breaches policy.
	entriesPayout := []domain.Entry{
		{AccountID: merchAccID, Amount: 5000, Direction: domain.DirectionDebit, Currency: "USD"},
		{AccountID: platAccID, Amount: 5000, Direction: domain.DirectionCredit, Currency: "USD"},
	}
	txPayout, err := domain.NewTransaction(
		uuid.New(),
		"client_policy",
		"key_payout_fail",
		sha256Hex("payout"),
		"Merchant Payout Overdraft Attempt",
		entriesPayout,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	// Pass overdraft limit = 10000 for platform so platform floor is not breached,
	// isolating the test for merchant credit balance check
	_, _, err = txRepo.RecordTransaction(ctx, txPayout, 10000)
	assert.ErrorIs(t, err, domain.ErrInsufficientFunds, "must reject debiting merchant with 0 balance")

	// 2. Platform overdraft limit breach
	// Platform normal balance is DEBIT. If overdraft limit is 1000 cents, debiting beyond -1000 breaches floor.
	entriesPlatformDrain := []domain.Entry{
		{AccountID: platAccID, Amount: 2000, Direction: domain.DirectionCredit, Currency: "USD"},
		{AccountID: custAccID, Amount: 2000, Direction: domain.DirectionDebit, Currency: "USD"},
	}
	txPlatformDrain, err := domain.NewTransaction(
		uuid.New(),
		"client_policy",
		"key_plat_drain",
		sha256Hex("drain"),
		"Platform Drain Attempt",
		entriesPlatformDrain,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	_, _, err = txRepo.RecordTransaction(ctx, txPlatformDrain, 1000) // overdraft limit = 1000, but deficit is 2000
	assert.ErrorIs(t, err, domain.ErrPlatformLiquidityBreached, "must reject breaching platform overdraft floor")
}

func TestIntegration_ReversalAndSingleReversalConstraint(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	accA := uuid.New()
	accB := uuid.New()
	accAObj, _ := domain.NewAccount(accA, "client_rev", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	accBObj, _ := domain.NewAccount(accB, "client_rev", domain.AccountTypeMerchant, "USD", time.Now().UTC())
	require.NoError(t, accountRepo.Create(ctx, accAObj))
	require.NoError(t, accountRepo.Create(ctx, accBObj))

	// Initial purchase: Cust Debit 1000, Merch Credit 1000
	entries := []domain.Entry{
		{AccountID: accA, Amount: 1000, Direction: domain.DirectionDebit, Currency: "USD"},
		{AccountID: accB, Amount: 1000, Direction: domain.DirectionCredit, Currency: "USD"},
	}
	origTxID := uuid.New()
	origTx, err := domain.NewTransaction(
		origTxID,
		"client_rev",
		"key_orig_tx",
		sha256Hex("orig"),
		"Initial Purchase",
		entries,
		time.Now().UTC(),
	)
	require.NoError(t, err)

	_, isNew, err := txRepo.RecordTransaction(ctx, origTx, 0)
	require.NoError(t, err)
	assert.True(t, isNew)

	// Execute reversal
	revID := uuid.New()
	revTx, isNewRev, err := txRepo.ReverseTransaction(
		ctx,
		origTxID,
		revID,
		"client_rev",
		"key_rev_1",
		sha256Hex("rev_1"),
		"Reversal of Initial Purchase",
		0,
	)
	require.NoError(t, err)
	assert.True(t, isNewRev)
	assert.Equal(t, &origTxID, revTx.ReversalOf)

	// Check balances: both accounts must have net zero balance
	balA, err := accountRepo.GetBalance(ctx, accA)
	require.NoError(t, err)
	assert.Equal(t, int64(1000), balA.Debits)
	assert.Equal(t, int64(1000), balA.Credits) // Customer net debit = 0

	balB, err := accountRepo.GetBalance(ctx, accB)
	require.NoError(t, err)
	assert.Equal(t, int64(1000), balB.Debits)
	assert.Equal(t, int64(1000), balB.Credits) // Merchant net credit = 0

	// Second attempt to reverse the same transaction: database unique constraint uq_transactions_reversal_of blocks it!
	_, _, err = txRepo.ReverseTransaction(
		ctx,
		origTxID,
		uuid.New(),
		"client_rev",
		"key_rev_2",
		sha256Hex("rev_2"),
		"Duplicate Reversal Attempt",
		0,
	)
	assert.Error(t, err, "database unique constraint must block duplicate reversal")
}

func TestIntegration_DatabaseImmutabilityTriggers(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	accA := uuid.New()
	accB := uuid.New()
	accAObj, _ := domain.NewAccount(accA, "client_trg", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	accBObj, _ := domain.NewAccount(accB, "client_trg", domain.AccountTypeMerchant, "USD", time.Now().UTC())
	require.NoError(t, accountRepo.Create(ctx, accAObj))
	require.NoError(t, accountRepo.Create(ctx, accBObj))

	txEntity, err := domain.NewTransaction(
		uuid.New(),
		"client_trg",
		"key_trg",
		sha256Hex("trg"),
		"Trigger Test",
		[]domain.Entry{
			{AccountID: accA, Amount: 100, Direction: domain.DirectionDebit, Currency: "USD"},
			{AccountID: accB, Amount: 100, Direction: domain.DirectionCredit, Currency: "USD"},
		},
		time.Now().UTC(),
	)
	require.NoError(t, err)

	recordedTx, _, err := txRepo.RecordTransaction(ctx, txEntity, 0)
	require.NoError(t, err)

	// Attempt direct SQL UPDATE on transactions table: must fail by trigger
	_, err = db.ExecContext(ctx, "UPDATE transactions SET description = 'Tampered' WHERE id = $1", recordedTx.ID)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "ledger immutability violation")

	// Attempt direct SQL DELETE on transactions table: must fail by trigger
	_, err = db.ExecContext(ctx, "DELETE FROM transactions WHERE id = $1", recordedTx.ID)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "ledger immutability violation")

	// Attempt direct SQL UPDATE on entries table: must fail by trigger
	_, err = db.ExecContext(ctx, "UPDATE entries SET amount = 9999 WHERE transaction_id = $1", recordedTx.ID)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "ledger immutability violation")

	// Attempt direct SQL DELETE on entries table: must fail by trigger
	_, err = db.ExecContext(ctx, "DELETE FROM entries WHERE transaction_id = $1", recordedTx.ID)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "ledger immutability violation")
}

func TestIntegration_DeferredConstraintTriggers(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	ctx := context.Background()

	// 1. Test trg_verify_transaction_min_entries: inserting a transaction with 0 or 1 entries at COMMIT
	t.Run("transaction with fewer than 2 entries fails at commit", func(t *testing.T) {
		tx, err := db.BeginTx(ctx, nil)
		require.NoError(t, err)
		defer tx.Rollback()

		orphanTxID := uuid.New()
		_, err = tx.ExecContext(ctx, `
			INSERT INTO transactions (id, client_id, idempotency_key, request_hash, description, created_at)
			VALUES ($1, 'client_c', 'orphan_key', $2, 'Orphan Tx', NOW())
		`, orphanTxID, sha256Hex("orphan"))
		require.NoError(t, err)

		// Commit without inserting entries: deferred trigger must abort commit!
		err = tx.Commit()
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "must have at least 2 entries")
	})

	// 2. Test trg_verify_entries_balance_and_currency: inserting unbalanced entries at COMMIT
	t.Run("unbalanced entries fail at commit", func(t *testing.T) {
		accountRepo := postgres.NewAccountRepository(db)
		accA := uuid.New()
		accB := uuid.New()
		accAObj, _ := domain.NewAccount(accA, "client_unb", domain.AccountTypeCustomer, "USD", time.Now().UTC())
		accBObj, _ := domain.NewAccount(accB, "client_unb", domain.AccountTypeMerchant, "USD", time.Now().UTC())
		require.NoError(t, accountRepo.Create(ctx, accAObj))
		require.NoError(t, accountRepo.Create(ctx, accBObj))

		sqlTx, err := db.BeginTx(ctx, nil)
		require.NoError(t, err)
		defer sqlTx.Rollback()

		unbTxID := uuid.New()
		_, err = sqlTx.ExecContext(ctx, `
			INSERT INTO transactions (id, client_id, idempotency_key, request_hash, description, created_at)
			VALUES ($1, 'client_unb', 'unbalanced_key', $2, 'Unbalanced Tx', NOW())
		`, unbTxID, sha256Hex("unbalanced"))
		require.NoError(t, err)

		// Insert unbalanced entries: Debit 1000 vs Credit 999
		_, err = sqlTx.ExecContext(ctx, `
			INSERT INTO entries (id, transaction_id, account_id, amount, direction, currency, created_at)
			VALUES 
				(gen_random_uuid(), $1, $2, 1000, 'DEBIT', 'USD', NOW()),
				(gen_random_uuid(), $1, $3, 999, 'CREDIT', 'USD', NOW())
		`, unbTxID, accA, accB)
		require.NoError(t, err)

		// Commit: deferred trigger must abort commit!
		err = sqlTx.Commit()
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "is unbalanced: debit minus credit diff is 1")
	})
}

func TestIntegration_ConcurrentTransactionsStressTest(t *testing.T) {
	db, teardown := setupTestDB(t)
	defer teardown()

	accountRepo := postgres.NewAccountRepository(db)
	txRepo := postgres.NewTransactionRepository(db)
	ctx := context.Background()

	// Create 4 shared accounts: Customer, Merchant, Platform, Fees
	custID := uuid.New()
	merchID := uuid.New()
	platID := uuid.New()
	feesID := uuid.New()

	custAcc, _ := domain.NewAccount(custID, "client_stress", domain.AccountTypeCustomer, "USD", time.Now().UTC())
	merchAcc, _ := domain.NewAccount(merchID, "client_stress", domain.AccountTypeMerchant, "USD", time.Now().UTC())
	platAcc, _ := domain.NewAccount(platID, "client_stress", domain.AccountTypePlatform, "USD", time.Now().UTC())
	feesAcc, _ := domain.NewAccount(feesID, "client_stress", domain.AccountTypeFees, "USD", time.Now().UTC())

	require.NoError(t, accountRepo.Create(ctx, custAcc))
	require.NoError(t, accountRepo.Create(ctx, merchAcc))
	require.NoError(t, accountRepo.Create(ctx, platAcc))
	require.NoError(t, accountRepo.Create(ctx, feesAcc))

	// Launch 50 concurrent transactions touching overlapping accounts
	concurrency := 50
	var wg sync.WaitGroup
	errs := make([]error, concurrency)

	for i := 0; i < concurrency; i++ {
		wg.Add(1)
		go func(idx int) {
			defer wg.Done()
			entries := []domain.Entry{
				{AccountID: custID, Amount: 100, Direction: domain.DirectionDebit, Currency: "USD"},
				{AccountID: merchID, Amount: 95, Direction: domain.DirectionCredit, Currency: "USD"},
				{AccountID: feesID, Amount: 5, Direction: domain.DirectionCredit, Currency: "USD"},
			}
			key := fmt.Sprintf("stress_tx_%d", idx)
			txEntity, err := domain.NewTransaction(
				uuid.New(),
				"client_stress",
				key,
				sha256Hex(key),
				fmt.Sprintf("Stress Transfer %d", idx),
				entries,
				time.Now().UTC(),
			)
			if err != nil {
				errs[idx] = err
				return
			}

			_, _, err = txRepo.RecordTransaction(ctx, txEntity, 0)
			errs[idx] = err
		}(i)
	}

	wg.Wait()

	// Assert zero errors and zero deadlocks!
	for i, err := range errs {
		require.NoError(t, err, "concurrent transaction %d failed", i)
	}

	// Verify global ledger balance invariant:
	// Sum(Debits) must equal Sum(Credits) across all accounts in the database
	var totalDebits, totalCredits int64
	err := db.QueryRowContext(ctx, `
		SELECT 
			COALESCE(SUM(CASE WHEN direction = 'DEBIT' THEN amount ELSE 0 END), 0),
			COALESCE(SUM(CASE WHEN direction = 'CREDIT' THEN amount ELSE 0 END), 0)
		FROM entries
	`).Scan(&totalDebits, &totalCredits)
	require.NoError(t, err)

	assert.Equal(t, int64(concurrency*100), totalDebits)
	assert.Equal(t, int64(concurrency*100), totalCredits)
	assert.Equal(t, totalDebits, totalCredits, "global ledger invariant violated after stress test")
}
